json.id user.id
json.email user.email
json.name user.name
json.ira user.ira
json.ira user.ira
json.registration_id user.registration_id
json.avatar user.avatar.url
json.created_at user.created_at
json.updated_at user.updated_at